name: yu_health_admin
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.0.0
  get: ^4.6.6
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
  
  fonts:
  - family: PlusJakarta
    fonts:
      - asset: assets/fonts/PlusJakarta.ttf
      - asset: assets/fonts/PlusJakartaItalic.ttf
        style: italic
  
  - family: Instrument
    fonts:
      - asset: assets/fonts/Instrument.ttf
      - asset: assets/fonts/InstrumentItalic.ttf
        style: italic
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter.ttf